Feature/#11
ormi-sideprojects/ormi-stackoverflow-server pull request #17
Opened 2024-06-19 13:51 UTC by little6523

웹 소켓 제외하고 구현 완료했습니다. 확인 부탁드립니다.

2024-06-25 16:06 UTC, devdynam0507 requested changes
**수고하셨어여 코멘트는 확인 부탁드립니다 !**

2024-06-25 16:06 UTC, devdynam0507 commented on src/main/java/org/ormi/stackorflow/infra/notification/NotificationRepository.java
> +        return notificationEntities.stream()
Repository에서 Response 객체를 반환하는것보다 여기서는 그냥 Entity 자체를 반환하고 Presentation에서 매핑하는게 낫지 않을까용 ??

2024-06-26 12:50 UTC, little6523 commented on src/main/java/org/ormi/stackorflow/infra/notification/NotificationRepository.java
> +        return notificationEntities.stream()
인터넷 어디서 본건데 'Entity를 DTO처럼 쓰지 말아라' 라는 말을 봐서 그렇게 하긴 했어요.. 근데 제가 봐도 레이어 끼리는 Enity로만 하는게 더 맞는 거 같긴 합니다.

2024-06-27 07:14 UTC, little6523 commented on src/main/java/org/ormi/stackorflow/infra/notification/NotificationRepository.java
> +        return notificationEntities.stream()
Repository에서 Entity로 반환 및 Presentaion에서 매핑하도록 수정했습니당

2024-07-02 11:21 UTC, merged